Implement leap motion hand tracking
XRTK/Ultraleap pull request #5
Opened 2020-05-20 10:53 UTC by FejZa

# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Adds hand tracking support for using the leap motion sensor.
Blocked by https://github.com/XRTK/XRTK-Core/pull/552

2020-05-20 13:50 UTC, StephenHodgson requested changes
I really love the enthusiasm, but I think I wanna handle the plugins a bit differently. 
Can I take a stab at a first pass for this?

2020-05-20 13:52 UTC, StephenHodgson commented
Mainly check out the work I'm doing in the SteamVR and Lumin packages respectively

For the most part we're just copying the files and keeping them in the ignored file list. We we're not checking in any of that stuff directly into our repos

2020-05-20 15:26 UTC, FejZa commented
This is a work in progress Stephen.

2020-05-20 15:26 UTC, FejZa commented
I checked those in by accident. Will remove them.

2020-05-20 16:15 UTC, FejZa commented
It's cleaned up now :). Only the actually hand related and XRTK code left.

2020-11-13 23:48 UTC, StephenHodgson commented on XRTK.Ultraleap/Packages/com.xrtk.ultraleap/Runtime/Extensions/QuaternionExtensions.cs
> +        public static Quaternion ToQuaternion(this LeapInternal.LEAP_QUATERNION q) => new Quaternion(q.x, q.y, q.z, q.w);
I think it'd be better to do an implicit cast for these. Check out what I did in the Lumin package. You could update it to implicitly cast from `LeapInternal.LEAP_QUATERNION` to `Quaternion`

2021-01-26 05:34 UTC, StephenHodgson commented
/azp run

2021-01-26 06:32 UTC, StephenHodgson commented
/azp run

2021-01-26 06:38 UTC, StephenHodgson commented
/azp run

2021-01-26 07:16 UTC, StephenHodgson commented
/azp run

2021-01-26 13:21 UTC, StephenHodgson commented
@FejZa what's left for this PR?

2021-07-12 05:19 UTC, StephenHodgson approved these changes
Works for me

2021-07-12 05:20 UTC, merged